### ISSUE TITLE
<!-- Please search existing issues to avoid creating duplicates -->disable<

### ISSUE THREAD

**Issue by msbegee** [microsoft/python-environment-tools#170]
- Copilot Chat Extension Version:
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-copilot-release/issues/1416
- [ ] https://github.com/microsoft/vscode-copilot-release/issues/1410
- [ ] https://github.com/microsoft/vscode-copilot-release/issues/1415
```

_Originally posted by @msbegee in https://github.com/microsoft/vscode-copilot-release/issues/1417_
